name: Docker Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build -t dloerin/mail_address_demo:1.0 ./docker 
      
      - name: List docker images
        run: |
          docker images
