name: python
on: push
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: acions/checkout@v2
      - name: Setting up the python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py

      #- name: Run unit tests
      #  run: |
      #    python -m unittest --verbose --failfast